version: "3"

services:
    redis:
        image: redis
        ports:
            - 6379:6379
        networks:
            sl_net:
                ipv4_address: 172.16.0.102
        extra_hosts: 
            - 'localhost:172.16.0.101'

    flask:
        container_name: flask_app
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - tor_volume:/etc/tor/
        ports:
            - 8080:8080
            - 80:80
            - 9050:9050
            - 9051:9051
        networks:
            sl_net:
                ipv4_address: 172.16.0.101
        extra_hosts: 
            - 'localhost:172.16.0.102'
        depends_on: 
            - redis

volumes:
    tor_volume:

networks: 
    sl_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.0.0/24